Allow different ActorJobs to run in parallel
Because the ActorJob created a watcher Actor with a fixed name,
running multiple ActorJobs in parallel lead to an error when the second
ActorJob was run:

    akka.actor.InvalidActorNameException: actor name [ActorJobWatcher] is not unique!

To fix this the name for the watcher actor is based on the
child actor's name.